export enum DirectoryTag {
  FreeLaunch = "FREE_LAUNCH",
  PaidFeatures = "PAID_FEATURES",
  HighTraffic = "HIGH_TRAFFIC",
}

export interface DirectoryType {
  name: string;
  description: string;
  url: string;
  bgColor: string;
  domainRating: number;
  viewsPerMonth: number;
  tags: DirectoryTag[];
}

export const DIRECTORIES_V2: Array<DirectoryType> = [
  {
    name: "Product Hunt",
    description: "The largest community of makers launching new products daily",
    url: "https://www.producthunt.com",
    bgColor: "#ff6154",
    domainRating: 85,
    viewsPerMonth: 12500000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "BetaList",
    description: "Discover and get early access to tomorrow's startups",
    url: "https://betalist.com",
    bgColor: "#2e9a8e",
    domainRating: 72,
    viewsPerMonth: 850000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "TinyStartups",
    description: "Directory of profitable side projects and small startups",
    url: "https://www.tinystartups.com",
    bgColor: "#7e26b8",
    domainRating: 45,
    viewsPerMonth: 125000,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "StartupsFm",
    description: "Directory to launch your product",
    url: "https://www.startups.fm",
    bgColor: "#26b843",
    domainRating: 38,
    viewsPerMonth: 95000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Firsto",
    description: "Launch platform / Alternative to ProductHunt",
    url: "https://firsto.co",
    bgColor: "#ff6100",
    domainRating: 35,
    viewsPerMonth: 75000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Microlaunch",
    description: "Launch and discover micro SaaS products",
    url: "https://microlaunch.net",
    bgColor: "#335bda",
    domainRating: 42,
    viewsPerMonth: 110000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SideProjectors",
    description: "Community for indie makers and side project enthusiasts",
    url: "https://www.sideprojectors.com",
    bgColor: "#f1c40f",
    domainRating: 28,
    viewsPerMonth: 45000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Solopush",
    description: "Platform for solo entrepreneurs to showcase their work",
    url: "https://solopush.com",
    bgColor: "#e67e22",
    domainRating: 25,
    viewsPerMonth: 32000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SaaSHub",
    description: "Directory of SaaS products with reviews and alternatives",
    url: "https://www.saashub.com",
    bgColor: "#3498db",
    domainRating: 68,
    viewsPerMonth: 2200000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "OpenLaunch",
    description: "Startup launch platform",
    url: "https://open-launch.com/",
    bgColor: "#2489c8",
    domainRating: 22,
    viewsPerMonth: 18000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Uneed",
    description: "Discover tools you never knew you needed",
    url: "https://www.uneed.best",
    bgColor: "#1abc9c",
    domainRating: 48,
    viewsPerMonth: 380000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Huzzler",
    description: "Launch your startup and get discovered by early adopters",
    url: "https://huzzler.so",
    bgColor: "#c0392b",
    domainRating: 20,
    viewsPerMonth: 15000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "LaunchingNext",
    description: "Upcoming product launches and startup previews",
    url: "https://www.launchingnext.com",
    bgColor: "#d35400",
    domainRating: 32,
    viewsPerMonth: 65000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startupfa.me",
    description: "Startup directory focused on founder stories",
    url: "https://startupfa.me",
    bgColor: "#8e44ad",
    domainRating: 18,
    viewsPerMonth: 12000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "MakerThrive",
    description: "Project launch platform/community",
    url: "https://makerthrive.com/",
    bgColor: "#8e44ad",
    domainRating: 24,
    viewsPerMonth: 28000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "TinyLaunch",
    description: "Launch your startup to a small-to-medium audience",
    url: "https://www.tinylaun.ch/",
    bgColor: "#58982e",
    domainRating: 15,
    viewsPerMonth: 8500,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Resource.fyi",
    description: "Curated collection of startup resources and tools",
    url: "https://resource.fyi",
    bgColor: "#2c3e50",
    domainRating: 35,
    viewsPerMonth: 88000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AffordHunt",
    description: "Discover affordable alternatives to popular tools",
    url: "https://affordhunt.com",
    bgColor: "#f39c12",
    domainRating: 28,
    viewsPerMonth: 55000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "FindYourSaaS",
    description: "Find the perfect SaaS solution for your needs",
    url: "https://findyoursaas.com",
    bgColor: "#e74c3c",
    domainRating: 31,
    viewsPerMonth: 72000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AlternativeTo",
    description: "Find alternatives to software and web services",
    url: "https://alternativeto.net",
    bgColor: "#27ae60",
    domainRating: 78,
    viewsPerMonth: 4800000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Alternative.me",
    description: "Discover alternatives to popular apps and services",
    url: "https://alternative.me",
    bgColor: "#16a085",
    domainRating: 52,
    viewsPerMonth: 420000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "ProductBurst",
    description: "Showcase your product to early adopters and investors",
    url: "https://productburst.com",
    bgColor: "#9b59b6",
    domainRating: 26,
    viewsPerMonth: 38000,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "Steemhunt",
    description: "Hunt cool products and get rewarded",
    url: "https://steemhunt.com",
    bgColor: "#3498db",
    domainRating: 41,
    viewsPerMonth: 185000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "DevHunt",
    description: "A platform for developers to showcase their latest projects",
    url: "https://devhunt.org",
    bgColor: "#3456a8",
    domainRating: 33,
    viewsPerMonth: 92000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Peerlist",
    description: "Professional network for creators and builders",
    url: "https://peerlist.io",
    bgColor: "#00aa45",
    domainRating: 44,
    viewsPerMonth: 320000,
    tags: [DirectoryTag.FreeLaunch],
  },
];
