import {
  ArrowRight,
  Award,
  BookOpen,
  Briefcase,
  Code,
  Compass,
  Eye,
  Hash,
  Layers,
  Fan,
  Rocket,
  Circle,
  Search,
  Umbrella,
  Shield,
  Star,
  Target,
  Users,
  Zap,
  Earth,
} from "lucide-react";

export const DIRECTORIES = [
  {
    name: "Product Hunt",
    description: "The largest community of makers launching new products daily",
    url: "https://www.producthunt.com",
    icon: Rocket,
    category: "Launch Platform",
    bgColor: "#ff6154",
    iconColor: "#fafafa",
  },
  {
    name: "BetaList",
    description: "Discover and get early access to tomorrow's startups",
    url: "https://betalist.com",
    icon: Star,
    category: "Beta Testing",
    bgColor: "#2e9a8e",
    iconColor: "#ffffff",
  },
  {
    name: "TinyStartups",
    description: "Directory of profitable side projects and small startups",
    url: "https://www.tinystartups.com",
    icon: Zap,
    category: "Launch Platform",
    bgColor: "#7e26b8",
    iconColor: "#fafafa",
  },
  {
    name: "StartupsFm",
    description: "Directory to launch your product",
    url: "https://www.startups.fm",
    icon: Earth,
    category: "Launch Platform",
    bgColor: "#26b843",
    iconColor: "#fafafa",
  },
  {
    name: "Firsto",
    description: "Launch platform / Alternative to ProductHunt",
    url: "https://firsto.co",
    icon: Umbrella,
    category: "Launch Platform",
    bgColor: "#ff6100",
    iconColor: "#fafafa",
  },
  {
    name: "Microlaunch",
    description: "Launch and discover micro SaaS products",
    url: "https://microlaunch.net",
    icon: Target,
    category: "Micro SaaS",
    bgColor: "#335bda",
    iconColor: "#fafafa",
  },
  {
    name: "SideProjectors",
    description: "Community for indie makers and side project enthusiasts",
    url: "https://www.sideprojectors.com",
    icon: Briefcase,
    category: "Side Projects",
    bgColor: "#f1c40f",
    iconColor: "#fafafa",
  },
  {
    name: "Solopush",
    description: "Platform for solo entrepreneurs to showcase their work",
    url: "https://solopush.com",
    icon: Eye,
    category: "Solo Founders",
    bgColor: "#e67e22",
    iconColor: "#fafafa",
  },
  {
    name: "SaaSHub",
    description: "Directory of SaaS products with reviews and alternatives",
    url: "https://www.saashub.com",
    icon: Layers,
    category: "SaaS Directory",
    bgColor: "#3498db",
    iconColor: "#fafafa",
  },
  {
    name: "OpenLaunch",
    description: "Startup launch platform",
    url: "https://open-launch.com/",
    icon: Circle,
    category: "Launch Platform",
    bgColor: "#2489c8",
    iconColor: "#fafafa",
  },
  {
    name: "Uneed",
    description: "Discover tools you never knew you needed",
    url: "https://www.uneed.best",
    icon: Search,
    category: "Tool Discovery",
    bgColor: "#1abc9c",
    iconColor: "#fafafa",
  },
  {
    name: "Huzzler",
    description: "Launch your startup and get discovered by early adopters",
    url: "https://huzzler.so",
    icon: Award,
    category: "Launch Platform",
    bgColor: "#c0392b",
    iconColor: "#fafafa",
  },
  {
    name: "LaunchingNext",
    description: "Upcoming product launches and startup previews",
    url: "https://www.launchingnext.com",
    icon: ArrowRight,
    category: "Preview Platform",
    bgColor: "#d35400",
    iconColor: "#fafafa",
  },
  {
    name: "Startupfa.me",
    description: "Startup directory focused on founder stories",
    url: "https://startupfa.me",
    icon: Users,
    category: "Founder Stories",
    bgColor: "#8e44ad",
    iconColor: "#fafafa",
  },
  {
    name: "MakerThrive",
    description: "Project launch platform/community",
    url: "https://makerthrive.com/",
    icon: BookOpen,
    category: "Founder Stories",
    bgColor: "#8e44ad",
    iconColor: "#fafafa",
  },
  {
    name: "TinyLaunch",
    description: "Launch your startup to a small-to-medium audience",
    url: "https://www.tinylaun.ch/",
    icon: Fan,
    category: "Launch Platform",
    bgColor: "#58982e",
    iconColor: "#fafafa",
  },
  {
    name: "Resource.fyi",
    description: "Curated collection of startup resources and tools",
    url: "https://resource.fyi",
    icon: Compass,
    category: "Resources",
    bgColor: "#2c3e50",
    iconColor: "#fafafa",
  },
  {
    name: "AffordHunt",
    description: "Discover affordable alternatives to popular tools",
    url: "https://affordhunt.com",
    icon: Shield,
    category: "Alternatives",
    bgColor: "#f39c12",
    iconColor: "#fafafa",
  },
  {
    name: "FindYourSaaS",
    description: "Find the perfect SaaS solution for your needs",
    url: "https://findyoursaas.com",
    icon: Search,
    category: "SaaS Discovery",
    bgColor: "#e74c3c",
    iconColor: "#fafafa",
  },
  {
    name: "AlternativeTo",
    description: "Find alternatives to software and web services",
    url: "https://alternativeto.net",
    icon: Hash,
    category: "Alternatives",
    bgColor: "#27ae60",
    iconColor: "#fafafa",
  },
  {
    name: "Alternative.me",
    description: "Discover alternatives to popular apps and services",
    url: "https://alternative.me",
    icon: Layers,
    category: "Alternatives",
    bgColor: "#16a085",
    iconColor: "#fafafa",
  },
  {
    name: "ProductBurst",
    description: "Showcase your product to early adopters and investors",
    url: "https://productburst.com",
    icon: Star,
    category: "Launch Platform",
    bgColor: "#9b59b6",
    iconColor: "#fafafa",
  },
  {
    name: "Steemhunt",
    description: "Hunt cool products and get rewarded",
    url: "https://steemhunt.com",
    icon: Target,
    category: "Product Hunt",
    bgColor: "#3498db",
    iconColor: "#fafafa",
  },
  {
    name: "DevHunt",
    description: "A platform for developers to showcase their latest projects",
    url: "https://devhunt.org",
    icon: Code,
    category: "Developer Tools",
    bgColor: "#3456a8",
    iconColor: "#fafafa",
  },
  {
    name: "Peerlist",
    description: "Professional network for creators and builders",
    url: "https://peerlist.io",
    icon: Users,
    category: "Community",
    bgColor: "#00aa45",
    iconColor: "#fafafa",
  },
];
