export enum DirectoryTag {
  FreeLaunch = "FREE_LAUNCH",
  PaidFeatures = "PAID_FEATURES",
  HighTraffic = "HIGH_TRAFFIC",
  AI = "AI",
}

export interface DirectoryType {
  name: string;
  description: string;
  url: string;
  bgColor: string;
  domainRating: number;
  viewsPerMonth: number;
  tags: DirectoryTag[];
}

export const DIRECTORIES_V2: Array<DirectoryType> = [
  {
    name: "Product Hunt",
    description: "The largest community of makers launching new products daily",
    url: "https://www.producthunt.com",
    bgColor: "#ff6154",
    domainRating: 85,
    viewsPerMonth: 12500000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "BetaList",
    description: "Discover and get early access to tomorrow's startups",
    url: "https://betalist.com",
    bgColor: "#2e9a8e",
    domainRating: 72,
    viewsPerMonth: 850000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "TinyStartups",
    description: "Directory of profitable side projects and small startups",
    url: "https://www.tinystartups.com",
    bgColor: "#7e26b8",
    domainRating: 45,
    viewsPerMonth: 125000,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "StartupsFm",
    description: "Directory to launch your product",
    url: "https://www.startups.fm",
    bgColor: "#26b843",
    domainRating: 38,
    viewsPerMonth: 95000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Firsto",
    description: "Launch platform / Alternative to ProductHunt",
    url: "https://firsto.co",
    bgColor: "#ff6100",
    domainRating: 35,
    viewsPerMonth: 75000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Microlaunch",
    description: "Launch and discover micro SaaS products",
    url: "https://microlaunch.net",
    bgColor: "#335bda",
    domainRating: 42,
    viewsPerMonth: 110000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SideProjectors",
    description: "Community for indie makers and side project enthusiasts",
    url: "https://www.sideprojectors.com",
    bgColor: "#f1c40f",
    domainRating: 28,
    viewsPerMonth: 45000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Solopush",
    description: "Platform for solo entrepreneurs to showcase their work",
    url: "https://solopush.com",
    bgColor: "#e67e22",
    domainRating: 25,
    viewsPerMonth: 32000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SaaSHub",
    description: "Directory of SaaS products with reviews and alternatives",
    url: "https://www.saashub.com",
    bgColor: "#3498db",
    domainRating: 68,
    viewsPerMonth: 2200000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "OpenLaunch",
    description: "Startup launch platform",
    url: "https://open-launch.com/",
    bgColor: "#2489c8",
    domainRating: 22,
    viewsPerMonth: 18000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Uneed",
    description: "Discover tools you never knew you needed",
    url: "https://www.uneed.best",
    bgColor: "#1abc9c",
    domainRating: 48,
    viewsPerMonth: 380000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Huzzler",
    description: "Launch your startup and get discovered by early adopters",
    url: "https://huzzler.so",
    bgColor: "#c0392b",
    domainRating: 20,
    viewsPerMonth: 15000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "LaunchingNext",
    description: "Upcoming product launches and startup previews",
    url: "https://www.launchingnext.com",
    bgColor: "#d35400",
    domainRating: 32,
    viewsPerMonth: 65000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startupfa.me",
    description: "Startup directory focused on founder stories",
    url: "https://startupfa.me",
    bgColor: "#8e44ad",
    domainRating: 18,
    viewsPerMonth: 12000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "MakerThrive",
    description: "Project launch platform/community",
    url: "https://makerthrive.com/",
    bgColor: "#8e44ad",
    domainRating: 24,
    viewsPerMonth: 28000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "TinyLaunch",
    description: "Launch your startup to a small-to-medium audience",
    url: "https://www.tinylaun.ch/",
    bgColor: "#58982e",
    domainRating: 15,
    viewsPerMonth: 8500,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Resource.fyi",
    description: "Curated collection of startup resources and tools",
    url: "https://resource.fyi",
    bgColor: "#2c3e50",
    domainRating: 35,
    viewsPerMonth: 88000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AffordHunt",
    description: "Discover affordable alternatives to popular tools",
    url: "https://affordhunt.com",
    bgColor: "#f39c12",
    domainRating: 28,
    viewsPerMonth: 55000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "FindYourSaaS",
    description: "Find the perfect SaaS solution for your needs",
    url: "https://findyoursaas.com",
    bgColor: "#e74c3c",
    domainRating: 31,
    viewsPerMonth: 72000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AlternativeTo",
    description: "Find alternatives to software and web services",
    url: "https://alternativeto.net",
    bgColor: "#27ae60",
    domainRating: 78,
    viewsPerMonth: 4800000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Alternative.me",
    description: "Discover alternatives to popular apps and services",
    url: "https://alternative.me",
    bgColor: "#16a085",
    domainRating: 52,
    viewsPerMonth: 420000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "ProductBurst",
    description: "Showcase your product to early adopters and investors",
    url: "https://productburst.com",
    bgColor: "#9b59b6",
    domainRating: 26,
    viewsPerMonth: 38000,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "Steemhunt",
    description: "Hunt cool products and get rewarded",
    url: "https://steemhunt.com",
    bgColor: "#3498db",
    domainRating: 41,
    viewsPerMonth: 185000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "DevHunt",
    description: "A platform for developers to showcase their latest projects",
    url: "https://devhunt.org",
    bgColor: "#3456a8",
    domainRating: 33,
    viewsPerMonth: 92000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Peerlist",
    description: "Professional network for creators and builders",
    url: "https://peerlist.io",
    bgColor: "#00aa45",
    domainRating: 44,
    viewsPerMonth: 320000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Peerlist",
    description: "Professional network for creators and builders",
    url: "https://opentools.ai",
    bgColor: "#00aa45",
    domainRating: 44,
    viewsPerMonth: 320000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "DevPost",
    description:
      "The world's largest community of developers and designers showcasing their projects",
    url: "https://devpost.com/software",
    bgColor: "#003e54",
    domainRating: 91,
    viewsPerMonth: 8500000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Product Hunt",
    description: "The largest community of makers launching new products daily",
    url: "https://www.producthunt.com/",
    bgColor: "#ff6154",
    domainRating: 80,
    viewsPerMonth: 12500000,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.HighTraffic,
      DirectoryTag.PaidFeatures,
    ],
  },
  {
    name: "Fazier",
    description: "Discover and submit new SaaS products and startup tools",
    url: "https://fazier.com/",
    bgColor: "#6366f1",
    domainRating: 19,
    viewsPerMonth: 45000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Lib",
    description: "Russian AI tools and resources directory",
    url: "https://ailib.ru/",
    bgColor: "#ef4444",
    domainRating: 28,
    viewsPerMonth: 120000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Hub",
    description: "Curated directory of AI tools and applications",
    url: "https://www.aihub.fyi/",
    bgColor: "#8b5cf6",
    domainRating: 27,
    viewsPerMonth: 85000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "GPTs Hunter",
    description: "Discover and explore custom GPT models and AI applications",
    url: "https://www.gptshunter.com/",
    bgColor: "#10b981",
    domainRating: 64,
    viewsPerMonth: 650000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Afford Hunt",
    description:
      "Affordable tools and resources for startups and entrepreneurs",
    url: "https://affordhunt.com/",
    bgColor: "#f59e0b",
    domainRating: 61,
    viewsPerMonth: 480000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "AI Finder",
    description: "Search and discover AI tools for various use cases",
    url: "https://ai-finder.net/",
    bgColor: "#06b6d4",
    domainRating: 59,
    viewsPerMonth: 420000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Launching Next",
    description:
      "Platform for discovering upcoming product launches and startups",
    url: "https://www.launchingnext.com/",
    bgColor: "#ec4899",
    domainRating: 56,
    viewsPerMonth: 380000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "Tool Directory",
    description: "AI-focused directory of productivity and business tools",
    url: "https://tooldirectory.ai/",
    bgColor: "#7c3aed",
    domainRating: 55,
    viewsPerMonth: 350000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Future Tools",
    description:
      "Comprehensive directory of AI tools and emerging technologies",
    url: "https://www.futuretools.io/",
    bgColor: "#0ea5e9",
    domainRating: 49,
    viewsPerMonth: 890000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Launched",
    description: "Showcase platform for new product launches and startups",
    url: "https://launched.io/",
    bgColor: "#84cc16",
    domainRating: 43,
    viewsPerMonth: 220000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "Startup Buffer",
    description: "Resources and tools directory for startup founders",
    url: "https://startupbuffer.com/",
    bgColor: "#f97316",
    domainRating: 41,
    viewsPerMonth: 180000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Insanely Cool Tools",
    description: "Curated collection of innovative tools and applications",
    url: "https://www.insanelycooltools.com/",
    bgColor: "#db2777",
    domainRating: 40,
    viewsPerMonth: 165000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "Io Directory",
    description: "Modern directory of web applications and digital tools",
    url: "https://yo.directory/",
    bgColor: "#059669",
    domainRating: 40,
    viewsPerMonth: 155000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SaaS AI Tools",
    description: "Directory focused on SaaS applications with AI capabilities",
    url: "https://saasaitools.com/",
    bgColor: "#7c2d12",
    domainRating: 38,
    viewsPerMonth: 145000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "AI Tool Guru",
    description: "Expert-curated AI tools and recommendations",
    url: "https://aitoolguru.com/",
    bgColor: "#be123c",
    domainRating: 36,
    viewsPerMonth: 125000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "DEV Resources",
    description: "Development tools and resources for programmers",
    url: "https://devresourc.es/",
    bgColor: "#1e40af",
    domainRating: 36,
    viewsPerMonth: 135000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Open Future",
    description: "Open-source AI tools and future technology directory",
    url: "https://openfuture.ai/",
    bgColor: "#16a34a",
    domainRating: 36,
    viewsPerMonth: 115000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "ChatGPT Demo",
    description: "Directory of ChatGPT demos and AI chat applications",
    url: "https://chatgptdemo.com/",
    bgColor: "#0d9488",
    domainRating: 35,
    viewsPerMonth: 280000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Mars AI Directory",
    description: "AI startup directory and emerging technology showcase",
    url: "https://www.marsx.dev/ai-startups",
    bgColor: "#dc2626",
    domainRating: 35,
    viewsPerMonth: 95000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Next Gen Tools",
    description: "Next-generation tools and applications directory",
    url: "https://nextgentools.me/",
    bgColor: "#9333ea",
    domainRating: 32,
    viewsPerMonth: 78000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "TipSeason AI Tools",
    description: "Seasonal collection of trending AI tools and tips",
    url: "https://tipseason.com/ai-tools",
    bgColor: "#ea580c",
    domainRating: 32,
    viewsPerMonth: 72000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Stage",
    description: "Platform for startup launches and early-stage companies",
    url: "https://startupstage.app/",
    bgColor: "#0891b2",
    domainRating: 30,
    viewsPerMonth: 65000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startups.fyi",
    description: "Startup directory and entrepreneurship resources",
    url: "https://www.startups.fyi/",
    bgColor: "#7c3aed",
    domainRating: 30,
    viewsPerMonth: 58000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup AI Tools",
    description: "AI tools specifically curated for startup environments",
    url: "https://www.startups.fyi/",
    bgColor: "#c2410c",
    domainRating: 27,
    viewsPerMonth: 52000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Apps and Websites",
    description: "Directory of web applications and useful websites",
    url: "https://appsandwebsites.com/",
    bgColor: "#22c55e",
    domainRating: 23,
    viewsPerMonth: 42000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "First 100 Users",
    description: "Platform to help startups find their first 100 users",
    url: "https://www.first100users.com/",
    bgColor: "#3b82f6",
    domainRating: 23,
    viewsPerMonth: 38000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "AI Library",
    description: "Comprehensive library of AI tools and resources",
    url: "https://library.phygital.plus/",
    bgColor: "#a855f7",
    domainRating: 22,
    viewsPerMonth: 35000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Draeno",
    description: "Modern tool discovery and productivity platform",
    url: "https://draeno.io/",
    bgColor: "#ef4444",
    domainRating: 22,
    viewsPerMonth: 32000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Tools.so",
    description: "Simple and clean directory of useful online tools",
    url: "https://tools.so/",
    bgColor: "#06b6d4",
    domainRating: 20,
    viewsPerMonth: 28000,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Radar",
    description: "Comprehensive AI tools directory for marketing professionals",
    url: "https://airadar.getinference.com/",
    bgColor: "#4f46e5",
    domainRating: 19,
    viewsPerMonth: 45000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "GPT Forge",
    description: "Platform for discovering and sharing GPT-powered tools",
    url: "https://gptforge.net/",
    bgColor: "#059669",
    domainRating: 19,
    viewsPerMonth: 38000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Marketing Directory",
    description: "Curated collection of AI marketing tools and resources",
    url: "https://aimarketing.directory/",
    bgColor: "#dc2626",
    domainRating: 17,
    viewsPerMonth: 28000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Live Apps",
    description: "Discover live AI applications and interactive tools",
    url: "https://liveapps.ai/",
    bgColor: "#7c3aed",
    domainRating: 17,
    viewsPerMonth: 32000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Tool Pilot",
    description: "Navigate the world of AI tools with expert guidance",
    url: "https://www.toolpilot.ai/",
    bgColor: "#ea580c",
    domainRating: 17,
    viewsPerMonth: 35000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Daily Tech AI",
    description: "Daily updates on the latest AI tools and technologies",
    url: "https://www.dailytech.ai/",
    bgColor: "#0891b2",
    domainRating: 16,
    viewsPerMonth: 25000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Free AI Tools Directory",
    description: "Comprehensive directory of free AI tools and resources",
    url: "https://free-ai-tools-directory.com/",
    bgColor: "#16a34a",
    domainRating: 16,
    viewsPerMonth: 42000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "The AI Generation",
    description: "Exploring the next generation of AI tools and applications",
    url: "https://www.theaigeneration.com/",
    bgColor: "#be185d",
    domainRating: 16,
    viewsPerMonth: 30000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Combined",
    description: "Unified platform combining various AI tools and services",
    url: "https://aicombined.com/",
    bgColor: "#9333ea",
    domainRating: 15,
    viewsPerMonth: 22000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Hunter",
    description: "Hunt for the best AI tools across different categories",
    url: "https://ai-hunter.io/",
    bgColor: "#c2410c",
    domainRating: 15,
    viewsPerMonth: 28000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI News Guru",
    description: "Latest AI news and curated app recommendations",
    url: "https://ainews.guru/apps/",
    bgColor: "#0d9488",
    domainRating: 15,
    viewsPerMonth: 20000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Search",
    description: "Intelligent search engine for AI tools and resources",
    url: "https://ai-search.io/",
    bgColor: "#1d4ed8",
    domainRating: 15,
    viewsPerMonth: 35000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tool NET",
    description: "Network of AI tools for various business applications",
    url: "https://www.aitoolnet.com/",
    bgColor: "#dc2626",
    domainRating: 15,
    viewsPerMonth: 24000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tools Directory COM",
    description: "Comprehensive directory of AI tools and applications",
    url: "https://aitoolsdirectory.com/",
    bgColor: "#059669",
    domainRating: 15,
    viewsPerMonth: 40000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tools Hunter",
    description: "Professional hunting ground for AI tools and solutions",
    url: "https://ai-hunter.io/",
    bgColor: "#7c2d12",
    domainRating: 15,
    viewsPerMonth: 26000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AIX Collection",
    description: "Curated collection of premium AI tools and resources",
    url: "https://aixcollection.com/",
    bgColor: "#4338ca",
    domainRating: 15,
    viewsPerMonth: 18000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Best AI Tools",
    description: "Discover the best AI tools for startups and businesses",
    url: "https://www.startupaitools.com/",
    bgColor: "#b91c1c",
    domainRating: 15,
    viewsPerMonth: 50000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Dev Pages",
    description: "Developer-focused directory of AI tools and resources",
    url: "https://www.devpages.io/",
    bgColor: "#374151",
    domainRating: 15,
    viewsPerMonth: 15000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Find Cool Tools",
    description: "Discover cool and innovative AI tools for every need",
    url: "https://findcool.tools/",
    bgColor: "#06b6d4",
    domainRating: 15,
    viewsPerMonth: 33000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Future AGI Tools",
    description: "Exploring the future of AGI and advanced AI tools",
    url: "https://www.futureagitools.com/",
    bgColor: "#7c3aed",
    domainRating: 15,
    viewsPerMonth: 16000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "GPT Stack",
    description: "Stack of GPT-powered tools and applications",
    url: "https://www.gpt-stack.com/",
    bgColor: "#059669",
    domainRating: 15,
    viewsPerMonth: 21000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "I Lib",
    description: "Library of intelligent AI tools and resources",
    url: "https://www.ilib.com/",
    bgColor: "#0891b2",
    domainRating: 15,
    viewsPerMonth: 12000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "SaasBaba",
    description: "Discover SaaS and AI tools for modern businesses",
    url: "https://saasbaba.com/",
    bgColor: "#ea580c",
    domainRating: 15,
    viewsPerMonth: 19000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Tools Directory",
    description: "Comprehensive directory of AI and productivity tools",
    url: "https://aitoolsdirectory.com/",
    bgColor: "#be185d",
    domainRating: 15,
    viewsPerMonth: 38000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "ToolScout",
    description: "Scout the best AI tools for your specific needs",
    url: "https://toolscout.ai/",
    bgColor: "#16a34a",
    domainRating: 15,
    viewsPerMonth: 27000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Warehouse AI",
    description: "Warehouse of AI tools and machine learning resources",
    url: "https://www.thewarehouse.ai/",
    bgColor: "#9333ea",
    domainRating: 15,
    viewsPerMonth: 14000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Top Rank",
    description: "Top-ranked AI tools and applications directory",
    url: "https://aitoprank.com/",
    bgColor: "#dc2626",
    domainRating: 13,
    viewsPerMonth: 11000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Look AI Tools",
    description: "Look for the perfect AI tools for your projects",
    url: "https://lookaitools.com/",
    bgColor: "#0d9488",
    domainRating: 11,
    viewsPerMonth: 8000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "SaasHub",
    description: "Comprehensive hub for SaaS and AI tool discovery",
    url: "https://www.saashub.com/",
    bgColor: "#1d4ed8",
    domainRating: 73,
    viewsPerMonth: 2800000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Tiny Startups",
    description: "Directory for small startups and AI tools",
    url: "https://www.tinystartups.co/",
    bgColor: "#059669",
    domainRating: 9,
    viewsPerMonth: 5500,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tools Up",
    description: "Level up your workflow with curated AI tools",
    url: "https://aitoolsup.com/",
    bgColor: "#7c3aed",
    domainRating: 7,
    viewsPerMonth: 3200,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "MicroLaunch",
    description: "Platform for launching and discovering micro AI tools",
    url: "https://microlaunch.net/",
    bgColor: "#ea580c",
    domainRating: 15,
    viewsPerMonth: 9000,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
];
