import mongoose from "mongoose";
import Directory, { DirectoryTag, SubmitDifficulty } from "../models/Directory";
import { DirectoryType } from "@/types/DirectoryType";

export const DIRECTORIES_V2: Array<DirectoryType> = [
  {
    name: "Product Hunt",
    description: "The largest community of makers launching new products daily",
    url: "https://www.producthunt.com",
    bgColor: "#ff6154",
    domainRating: 91,
    viewsPerMonth: 12500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "BetaList",
    description: "Discover and get early access to tomorrow's startups",
    url: "https://betalist.com",
    bgColor: "#2e9a8e",
    domainRating: 74,
    viewsPerMonth: 850000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "TinyStartups",
    description: "Directory of profitable side projects and small startups",
    url: "https://www.tinystartups.com",
    bgColor: "#7e26b8",
    domainRating: 47,
    viewsPerMonth: 125000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "StartupsFm",
    description: "Directory to launch your product",
    url: "https://www.startups.fm",
    bgColor: "#26b843",
    domainRating: 31,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Firsto",
    description: "Launch platform / Alternative to ProductHunt",
    url: "https://firsto.co",
    bgColor: "#ff6100",
    domainRating: 29,
    viewsPerMonth: 75000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Microlaunch",
    description: "Launch and discover micro SaaS products",
    url: "https://microlaunch.net",
    bgColor: "#335bda",
    domainRating: 52,
    viewsPerMonth: 110000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.SmallStartups],
  },
  {
    name: "SideProjectors",
    description: "Community for indie makers and side project enthusiasts",
    url: "https://www.sideprojectors.com",
    bgColor: "#f1c40f",
    domainRating: 71,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Solopush",
    description: "Platform for solo entrepreneurs to showcase their work",
    url: "https://solopush.com",
    bgColor: "#e67e22",
    domainRating: 43,
    viewsPerMonth: 32000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SaaSHub",
    description: "Directory of SaaS products with reviews and alternatives",
    url: "https://www.saashub.com",
    bgColor: "#3498db",
    domainRating: 74,
    viewsPerMonth: 2200000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "OpenLaunch",
    description: "Startup launch platform",
    url: "https://open-launch.com/",
    bgColor: "#2489c8",
    domainRating: 34,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Uneed",
    description: "Discover tools you never knew you needed",
    url: "https://www.uneed.best",
    bgColor: "#1abc9c",
    domainRating: 66,
    viewsPerMonth: 380000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Huzzler",
    description: "Launch your startup and get discovered by early adopters",
    url: "https://huzzler.so",
    bgColor: "#c0392b",
    domainRating: 31,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "LaunchingNext",
    description: "Upcoming product launches and startup previews",
    url: "https://www.launchingnext.com",
    bgColor: "#d35400",
    domainRating: 50,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startupfa.me",
    description: "Startup directory focused on founder stories",
    url: "https://startupfa.me",
    bgColor: "#8e44ad",
    domainRating: 75,
    viewsPerMonth: 12000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "MakerThrive",
    description: "Project launch platform/community",
    url: "https://makerthrive.com/",
    bgColor: "#8e44ad",
    domainRating: 47,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "TinyLaunch",
    description: "Launch your startup to a small-to-medium audience",
    url: "https://www.tinylaun.ch/",
    bgColor: "#58982e",
    domainRating: 60,
    viewsPerMonth: 8500,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Resource.fyi",
    description: "Curated collection of startup resources and tools",
    url: "https://resource.fyi",
    bgColor: "#2c3e50",
    domainRating: 37,
    viewsPerMonth: 88000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AffordHunt",
    description: "Discover affordable alternatives to popular tools",
    url: "https://affordhunt.com",
    bgColor: "#f39c12",
    domainRating: 29,
    viewsPerMonth: 55000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "FindYourSaaS",
    description: "Find the perfect SaaS solution for your needs",
    url: "https://findyoursaas.com",
    bgColor: "#e74c3c",
    domainRating: 9,
    viewsPerMonth: 72000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AlternativeTo",
    description: "Find alternatives to software and web services",
    url: "https://alternativeto.net",
    bgColor: "#27ae60",
    domainRating: 80,
    viewsPerMonth: 4800000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Alternative.me",
    description: "Discover alternatives to popular apps and services",
    url: "https://alternative.me",
    bgColor: "#16a085",
    domainRating: 73,
    viewsPerMonth: 420000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "ProductBurst",
    description: "Showcase your product to early adopters and investors",
    url: "https://productburst.com",
    bgColor: "#9b59b6",
    domainRating: 47,
    viewsPerMonth: 38000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "Steemhunt",
    description: "Hunt cool products and get rewarded",
    url: "https://steemhunt.com",
    bgColor: "#3498db",
    domainRating: 41,
    viewsPerMonth: 185000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "DevHunt",
    description: "A platform for developers to showcase their latest projects",
    url: "https://devhunt.org",
    bgColor: "#3456a8",
    domainRating: 58,
    viewsPerMonth: 92000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Peerlist",
    description: "Professional network for creators and builders",
    url: "https://peerlist.io",
    bgColor: "#00aa45",
    domainRating: 69,
    viewsPerMonth: 320000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "DevPost",
    description:
      "The world's largest community of developers and designers showcasing their projects",
    url: "https://devpost.com/software",
    bgColor: "#003e54",
    domainRating: 86,
    viewsPerMonth: 8500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Fazier",
    description: "Discover and submit new SaaS products and startup tools",
    url: "https://fazier.com/",
    bgColor: "#6366f1",
    domainRating: 67,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "GPTs Hunter",
    description: "Discover and explore custom GPT models and AI applications",
    url: "https://www.gptshunter.com/",
    bgColor: "#10b981",
    domainRating: 57,
    viewsPerMonth: 650000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Tool Directory",
    description: "AI-focused directory of productivity and business tools",
    url: "https://tooldirectory.ai/",
    bgColor: "#7c3aed",
    domainRating: 53,
    viewsPerMonth: 350000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Future Tools",
    description:
      "Comprehensive directory of AI tools and emerging technologies",
    url: "https://www.futuretools.io/",
    bgColor: "#0ea5e9",
    domainRating: 64,
    viewsPerMonth: 890000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Launched",
    description: "Showcase platform for new product launches and startups",
    url: "https://launched.io/",
    bgColor: "#84cc16",
    domainRating: 39,
    viewsPerMonth: 220000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "Startup Buffer",
    description: "Resources and tools directory for startup founders",
    url: "https://startupbuffer.com/",
    bgColor: "#f97316",
    domainRating: 42,
    viewsPerMonth: 180000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Yo Directory",
    description: "Modern directory of web applications and digital tools",
    url: "https://yo.directory/",
    bgColor: "#059669",
    domainRating: 44,
    viewsPerMonth: 155000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SaaS AI Tools",
    description: "Directory focused on SaaS applications with AI capabilities",
    url: "https://saasaitools.com/",
    bgColor: "#7c2d12",
    domainRating: 53,
    viewsPerMonth: 145000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "AI Tool Guru",
    description: "Expert-curated AI tools and recommendations",
    url: "https://aitoolguru.com/",
    bgColor: "#be123c",
    domainRating: 29,
    viewsPerMonth: 125000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "DEV Resources",
    description: "Development tools and resources for programmers",
    url: "https://devresourc.es/",
    bgColor: "#1e40af",
    domainRating: 33,
    viewsPerMonth: 135000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Open Future",
    description: "Open-source AI tools and future technology directory",
    url: "https://openfuture.ai/",
    bgColor: "#16a34a",
    domainRating: 31,
    viewsPerMonth: 115000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "ChatGPT Demo",
    description: "Directory of ChatGPT demos and AI chat applications",
    url: "https://chatgptdemo.com/",
    bgColor: "#0d9488",
    domainRating: 31,
    viewsPerMonth: 280000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Mars AI Directory",
    description: "AI startup directory and emerging technology showcase",
    url: "https://www.marsx.dev/ai-startups",
    bgColor: "#dc2626",
    domainRating: 43,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Next Gen Tools",
    description: "Next-generation tools and applications directory",
    url: "https://nextgentools.me/",
    bgColor: "#9333ea",
    domainRating: 8,
    viewsPerMonth: 78000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "TipSeason AI Tools",
    description: "Seasonal collection of trending AI tools and tips",
    url: "https://tipseason.com/ai-tools",
    bgColor: "#ea580c",
    domainRating: 23,
    viewsPerMonth: 72000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Startups.fyi",
    description: "Startup directory and entrepreneurship resources",
    url: "https://www.startups.fyi/",
    bgColor: "#7c3aed",
    domainRating: 25,
    viewsPerMonth: 58000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Apps and Websites",
    description: "Directory of web applications and useful websites",
    url: "https://appsandwebsites.com/",
    bgColor: "#22c55e",
    domainRating: 22,
    viewsPerMonth: 42000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "First 100 Users",
    description: "Platform to help startups find their first 100 users",
    url: "https://www.first100users.com/",
    bgColor: "#3b82f6",
    domainRating: 21,
    viewsPerMonth: 38000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "AI Library",
    description: "Comprehensive library of AI tools and resources",
    url: "https://library.phygital.plus/",
    bgColor: "#a855f7",
    domainRating: 47,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Marketing Directory",
    description: "Curated collection of AI marketing tools and resources",
    url: "https://aimarketing.directory/",
    bgColor: "#dc2626",
    domainRating: 9,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Tool Pilot",
    description: "Navigate the world of AI tools with expert guidance",
    url: "https://www.toolpilot.ai/",
    bgColor: "#ea580c",
    domainRating: 72,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Free AI Tools Directory",
    description: "Comprehensive directory of free AI tools and resources",
    url: "https://free-ai-tools-directory.com/",
    bgColor: "#16a34a",
    domainRating: 8,
    viewsPerMonth: 42000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "The AI Generation",
    description: "Exploring the next generation of AI tools and applications",
    url: "https://www.theaigeneration.com/",
    bgColor: "#be185d",
    domainRating: 5,
    viewsPerMonth: 30000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Hunter",
    description: "Hunt for the best AI tools across different categories",
    url: "https://ai-hunter.io/",
    bgColor: "#c2410c",
    domainRating: 20,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Search",
    description: "Intelligent search engine for AI tools and resources",
    url: "https://ai-search.io/",
    bgColor: "#1d4ed8",
    domainRating: 22,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tool NET",
    description: "Network of AI tools for various business applications",
    url: "https://www.aitoolnet.com/",
    bgColor: "#dc2626",
    domainRating: 58,
    viewsPerMonth: 24000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tools Directory",
    description: "Comprehensive directory of AI tools and applications",
    url: "https://aitoolsdirectory.com/",
    bgColor: "#059669",
    domainRating: 41,
    viewsPerMonth: 40000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Best AI Tools",
    description: "Discover the best AI tools for startups and businesses",
    url: "https://www.startupaitools.com/",
    bgColor: "#b91c1c",
    domainRating: 12,
    viewsPerMonth: 50000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Dev Pages",
    description: "Developer-focused directory of AI tools and resources",
    url: "https://www.devpages.io/",
    bgColor: "#374151",
    domainRating: 29,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Future AGI Tools",
    description: "Exploring the future of AGI and advanced AI tools",
    url: "https://www.futureagitools.com/",
    bgColor: "#7c3aed",
    domainRating: 7,
    viewsPerMonth: 16000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "SaasBaba",
    description: "Discover SaaS and AI tools for modern businesses",
    url: "https://saasbaba.com/",
    bgColor: "#ea580c",
    domainRating: 13,
    viewsPerMonth: 19000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "ToolScout",
    description: "Scout the best AI tools for your specific needs",
    url: "https://toolscout.ai/",
    bgColor: "#16a34a",
    domainRating: 18,
    viewsPerMonth: 27000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Look AI Tools",
    description: "Look for the perfect AI tools for your projects",
    url: "https://lookaitools.com/",
    bgColor: "#0d9488",
    domainRating: 19,
    viewsPerMonth: 8000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Tools Up",
    description: "Level up your workflow with curated AI tools",
    url: "https://aitoolsup.com/",
    bgColor: "#7c3aed",
    domainRating: 5,
    viewsPerMonth: 3200,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "WTF Craft",
    description: "Level up your workflow with curated AI tools",
    url: "https://wtcraft.com/",
    bgColor: "#3c3aed",
    domainRating: 29,
    viewsPerMonth: 3200,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Grow Startup",
    description: "Level up your workflow with curated AI tools",
    url: "https://growstartup.co/",
    bgColor: "#1c2aed",
    domainRating: 2,
    viewsPerMonth: 3200,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startups Gallery",
    description:
      "Discover top early-stage startups funded by leading investors like Y Combinator, Sequoia, and a16z",
    url: "https://startups.gallery/",
    bgColor: "#1a1a1a",
    domainRating: 16,
    viewsPerMonth: 85000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Find Top AI Tools",
    description:
      "Discover and explore the best AI tools and applications for your business and personal use",
    url: "https://findtopaitools.com/",
    bgColor: "#2563eb",
    domainRating: 1,
    viewsPerMonth: 120000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "Indie Tool",
    description:
      "Discover and showcase apps built by solopreneurs and indie hackers. Get valuable backlinks and enhance SEO",
    url: "https://www.indietool.io/",
    bgColor: "#f59e0b",
    domainRating: 30,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Tool Battles",
    description:
      "Discover your next favorite tech products & tools like software, SaaS, Apps, and Consumer tech",
    url: "https://toolbattles.com/",
    bgColor: "#ef4444",
    domainRating: 13,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Stash",
    description:
      "World's largest online directory of tools and resources for startups to build killer products",
    url: "https://startupstash.com/",
    bgColor: "#06b6d4",
    domainRating: 68,
    viewsPerMonth: 380000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "1000 Tools",
    description:
      "Comprehensive directory of 1000+ tools and resources for entrepreneurs and startups",
    url: "https://1000.tools/",
    bgColor: "#8b5cf6",
    domainRating: 28,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Base",
    description:
      "Platform for discovering and launching startups with comprehensive startup resources and networking",
    url: "https://startupbase.io/",
    bgColor: "#10b981",
    domainRating: 52,
    viewsPerMonth: 55000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Buffer Apps",
    description:
      "Curated collection of productivity apps and tools to streamline your workflow and boost efficiency",
    url: "https://bufferapps.com/",
    bgColor: "#3b82f6",
    domainRating: 19,
    viewsPerMonth: 32000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "OpenTools AI",
    description:
      "Curated collection of productivity apps and tools to streamline your workflow and boost efficiency",
    url: "https://opentools.ai/",
    bgColor: "#3b82f6",
    domainRating: 52,
    viewsPerMonth: 32000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.AI, DirectoryTag.FreeLaunch],
  },
  {
    name: "Toolio AI",
    description:
      "Discover 9000+ tools for social media, no-code app building, automation, and productivity enhancement",
    url: "https://www.toolio.ai/",
    bgColor: "#7c3aed",
    domainRating: 40,
    viewsPerMonth: 125000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "There's An AI For That",
    description:
      "The #1 website for AI tools used by 60 million people to find the right AI tool for any task",
    url: "https://theresanaiforthat.com/",
    bgColor: "#059669",
    domainRating: 75,
    viewsPerMonth: 2500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI, DirectoryTag.HighTraffic],
  },
  {
    name: "TopAI Tools",
    description:
      "Curated list of best AI applications to boost productivity, updated daily with latest AI tools",
    url: "https://topai.tools/",
    bgColor: "#dc2626",
    domainRating: 59,
    viewsPerMonth: 450000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI, DirectoryTag.HighTraffic],
  },
  {
    name: "That AI Collection",
    description:
      "Comprehensive collection of AI tools and resources organized by categories and use cases",
    url: "https://www.thataicollection.com/",
    bgColor: "#2563eb",
    domainRating: 34,
    viewsPerMonth: 180000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "Open Alternative",
    description:
      "Open source alternatives to popular software and SaaS tools for developers and businesses",
    url: "https://openalternative.co/",
    bgColor: "#16a34a",
    domainRating: 46,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Based Tools AI",
    description:
      "Curated directory of AI tools and applications focused on practical business solutions",
    url: "https://www.basedtools.ai/",
    bgColor: "#f59e0b",
    domainRating: 45,
    viewsPerMonth: 85000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "AI Tool Hunt",
    description:
      "Comprehensive directory of the best free AI tools, software, and websites for digital enhancement",
    url: "https://www.aitoolhunt.com/",
    bgColor: "#8b5cf6",
    domainRating: 49,
    viewsPerMonth: 220000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI],
  },
  {
    name: "Appscribed",
    description:
      "Discover and review the best apps and software tools for productivity and business growth",
    url: "https://appscribed.com/",
    bgColor: "#06b6d4",
    domainRating: 47,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "10words",
    description: "Pitch your startup in exactly 10 words",
    url: "https://10words.io",
    bgColor: "#2563eb",
    domainRating: 32,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AI Collection",
    description: "Curated collection of the best AI tools and resources",
    url: "https://www.thataicollection.com/",
    bgColor: "#7c3aed",
    domainRating: 34,
    viewsPerMonth: 450000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.AI, DirectoryTag.HighTraffic],
  },
  {
    name: "All My Faves",
    description: "Visual bookmark manager and startup discovery platform",
    url: "https://www.allmyfaves.com/",
    bgColor: "#f59e0b",
    domainRating: 73,
    viewsPerMonth: 280000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "All Startups Info",
    description: "Directory for startups to submit and get discovered",
    url: "http://www.allstartups.info/Startups/Submit",
    bgColor: "#10b981",
    domainRating: 35,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "All Startups Com",
    description: "Submit your startup to get featured among top startups",
    url: "http://alltopstartups.com/submit-startup/",
    bgColor: "#3b82f6",
    domainRating: 64,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AngelList",
    description:
      "The world's largest startup community for fundraising and talent",
    url: "https://angel.co/",
    bgColor: "#000000",
    domainRating: 90,
    viewsPerMonth: 8500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.PaidFeatures,
      DirectoryTag.HighTraffic,
    ],
  },
  {
    name: "AppAdvice",
    description: "App discovery and recommendation platform",
    url: "http://appadvice.com/",
    bgColor: "#3b82f6",
    domainRating: 80,
    viewsPerMonth: 750000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "App Rater",
    description: "Submit your app for review and rating",
    url: "https://apprater.net/add/",
    bgColor: "#f59e0b",
    domainRating: 16,
    viewsPerMonth: 25000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Appoid",
    description: "Submit your app for professional review",
    url: "http://appiod.com/submit-app-for-review/",
    bgColor: "#06b6d4",
    domainRating: 32,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "appPicker",
    description: "App recommendation and discovery service",
    url: "http://www.apppicker.com/",
    bgColor: "#ef4444",
    domainRating: 62,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Apps 400",
    description: "Submit your application for review and exposure",
    url: "http://apps400.com/submit-your-application-for-review",
    bgColor: "#8b5cf6",
    domainRating: 42,
    viewsPerMonth: 12000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Apps Listo",
    description: "App submission and discovery platform",
    url: "http://appslisto.com/submit-your-app/",
    bgColor: "#10b981",
    domainRating: 12,
    viewsPerMonth: 22000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Apps Mamma",
    description: "Mobile app submission and review service",
    url: "http://appsmamma.com/submit-your-app/",
    bgColor: "#f97316",
    domainRating: 14,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "AppsThunder",
    description: "Get your app reviewed and featured",
    url: "http://appsthunder.com/submit-your-app/",
    bgColor: "#1d4ed8",
    domainRating: 27,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Appvita",
    description: "App discovery and recommendation platform",
    url: "http://www.appvita.com/",
    bgColor: "#059669",
    domainRating: 44,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Arctic Startup",
    description: "Nordic startup community and news platform",
    url: "http://arcticstartup.com/",
    bgColor: "#0ea5e9",
    domainRating: 66,
    viewsPerMonth: 125000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Awesome Indie",
    description: "Showcase for independent makers and their projects",
    url: "https://awesomeindie.com",
    bgColor: "#7c2d12",
    domainRating: 19,
    viewsPerMonth: 55000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Beta Bound",
    description: "Beta testing community for new products",
    url: "http://www.betabound.com/announce/",
    bgColor: "#dc2626",
    domainRating: 54,
    viewsPerMonth: 85000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Beta Page",
    description: "Landing page builder for beta launches",
    url: "https://betapage.co/",
    bgColor: "#2563eb",
    domainRating: 63,
    viewsPerMonth: 120000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "Beta Testing",
    description: "Professional beta testing services",
    url: "https://betatesting.com/beta-testing",
    bgColor: "#7c3aed",
    domainRating: 61,
    viewsPerMonth: 180000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.PaidFeatures],
  },
  {
    name: "Boing Boing",
    description: "Tech culture blog and product discovery",
    url: "http://boingboing.net/sub/",
    bgColor: "#ef4444",
    domainRating: 85,
    viewsPerMonth: 4200000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Broadwise.org",
    description: "Business directory and startup showcase",
    url: "https://broadwise.org/",
    bgColor: "#0891b2",
    domainRating: 11,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Collaborizm",
    description: "Collaboration platform for entrepreneurs and creators",
    url: "https://www.collaborizm.com",
    bgColor: "#6366f1",
    domainRating: 33,
    viewsPerMonth: 75000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "CrozDesk",
    description: "Business software discovery platform",
    url: "https://vendor.crozdesk.com/",
    bgColor: "#059669",
    domainRating: 76,
    viewsPerMonth: 320000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "Crunchbase",
    description: "The definitive platform for startup and company information",
    url: "https://www.crunchbase.com/#/home/index",
    bgColor: "#0084ff",
    domainRating: 91,
    viewsPerMonth: 18500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.PaidFeatures,
      DirectoryTag.HighTraffic,
    ],
  },
  {
    name: "Discova",
    description: "Discover and share innovative products",
    url: "http://www.discova.co/",
    bgColor: "#8b5cf6",
    domainRating: 9,
    viewsPerMonth: 8000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Discover Cloud",
    description: "Cloud software discovery platform",
    url: "https://www.discovercloud.com/",
    bgColor: "#0ea5e9",
    domainRating: 41,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "eBool",
    description: "Submit your startup for discovery",
    url: "https://www.ebool.com/submit",
    bgColor: "#dc2626",
    domainRating: 61,
    viewsPerMonth: 5000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "F6S",
    description: "Global startup accelerator and founder network",
    url: "http://www.f6s.com/",
    bgColor: "#000000",
    domainRating: 83,
    viewsPerMonth: 1200000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Fiddy",
    description: "Minimal startup directory for indie makers",
    url: "https://fiddy.co",
    bgColor: "#f59e0b",
    domainRating: 24,
    viewsPerMonth: 12000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "G2",
    description: "Business software reviews and comparison platform",
    url: "https://www.g2crowd.com/products/new",
    bgColor: "#ff492c",
    domainRating: 83,
    viewsPerMonth: 25000000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.PaidFeatures,
      DirectoryTag.HighTraffic,
    ],
  },
  {
    name: "GeekWire",
    description: "Pacific Northwest tech news and startup coverage",
    url: "http://geekwire.com/startup-list/",
    bgColor: "#0066cc",
    domainRating: 86,
    viewsPerMonth: 1800000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "GetApp",
    description: "Business software discovery platform by Gartner",
    url: "http://getapp.com/",
    bgColor: "#1e40af",
    domainRating: 85,
    viewsPerMonth: 8500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.PaidFeatures,
      DirectoryTag.HighTraffic,
    ],
  },
  {
    name: "Getworm",
    description: "Submit your startup for discovery",
    url: "https://getworm.com/submit-startup",
    bgColor: "#10b981",
    domainRating: 30,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "GrowthBoosters",
    description: "Product launch and growth platform",
    url: "https://www.growthboosters.com/product/add",
    bgColor: "#059669",
    domainRating: 10,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Gust",
    description: "Global platform connecting startups with investors",
    url: "https://www.gust.com",
    bgColor: "#2563eb",
    domainRating: 78,
    viewsPerMonth: 450000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.PaidFeatures],
  },
  {
    name: "HARO",
    description: "Help a Reporter Out - media connection platform",
    url: "https://www.helpareporter.com/sources/",
    bgColor: "#dc2626",
    domainRating: 81,
    viewsPerMonth: 1200000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Hackerspad",
    description: "Software submission and discovery platform",
    url: "https://hackerspad.net/submit-software/",
    bgColor: "#7c3aed",
    domainRating: 9,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Inc42",
    description: "India's leading startup media platform",
    url: "https://inc42.com/startup-submission/",
    bgColor: "#ef4444",
    domainRating: 80,
    viewsPerMonth: 2800000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Indie Hackers",
    description:
      "Community of developers sharing revenue numbers and strategies",
    url: "https://www.indiehackers.com/",
    bgColor: "#0066ff",
    domainRating: 80,
    viewsPerMonth: 3500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Killer Startups",
    description: "Startup discovery and review platform",
    url: "http://killerstartups.com/submit-startup/",
    bgColor: "#dc2626",
    domainRating: 74,
    viewsPerMonth: 185000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Land-book",
    description: "Landing page design gallery and inspiration",
    url: "https://land-book.com",
    bgColor: "#000000",
    domainRating: 72,
    viewsPerMonth: 420000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Launched",
    description: "Startup launch and discovery platform",
    url: "https://launched.io/SubmitStartup",
    bgColor: "#6366f1",
    domainRating: 39,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Loop",
    description: "User feedback and product discovery platform",
    url: "https://app.loopinput.com/",
    bgColor: "#8b5cf6",
    domainRating: 19,
    viewsPerMonth: 22000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "MakeUseOf",
    description: "Technology news and product discovery",
    url: "http://www.makeuseof.com/about/",
    bgColor: "#1e40af",
    domainRating: 88,
    viewsPerMonth: 18500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Micro SaaS Examples",
    description: "Showcase of successful micro SaaS businesses",
    url: "https://www.microsaasexamples.com/",
    bgColor: "#059669",
    domainRating: 27,
    viewsPerMonth: 75000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Netted",
    description: "Curated web discoveries and product features",
    url: "https://www.netted.net",
    bgColor: "#ef4444",
    domainRating: 63,
    viewsPerMonth: 95000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Next Big What",
    description: "Indian startup ecosystem news and discovery",
    url: "http://nextbigwhat.com/",
    bgColor: "#f97316",
    domainRating: 66,
    viewsPerMonth: 320000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Postmake",
    description: "Maker community for launching and discovering products",
    url: "https://postmake.io/submit",
    bgColor: "#7c3aed",
    domainRating: 31,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "PreApps",
    description: "Preview upcoming mobile apps before launch",
    url: "http://www.preapps.com/",
    bgColor: "#3b82f6",
    domainRating: 53,
    viewsPerMonth: 55000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Project Hatch",
    description: "Share your startup story and get discovered",
    url: "https://www.projecthatch.co/your-story/",
    bgColor: "#10b981",
    domainRating: 36,
    viewsPerMonth: 25000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Projectium Network",
    description: "Project management and startup discovery platform",
    url: "https://projectium.network",
    bgColor: "#0ea5e9",
    domainRating: 19,
    viewsPerMonth: 12000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Saasified",
    description: "SaaS product discovery and reviews",
    url: "https://saasified.co",
    bgColor: "#8b5cf6",
    domainRating: 25,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Saijo's Tools List",
    description: "Curated list of the best marketing tools",
    url: "https://saijogeorge.com/best-marketing-tools/",
    bgColor: "#f59e0b",
    domainRating: 66,
    viewsPerMonth: 180000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Show HN",
    description: "Hacker News section for showing off projects",
    url: "https://news.ycombinator.com/showhn.html",
    bgColor: "#ff6600",
    domainRating: 90,
    viewsPerMonth: 8500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Side Projectors",
    description: "Showcase for side projects and indie makers",
    url: "https://www.sideprojectors.com",
    bgColor: "#7c2d12",
    domainRating: 71,
    viewsPerMonth: 22000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Simple Lister",
    description: "Simple directory for listing your startup",
    url: "https://simplelister.com/",
    bgColor: "#059669",
    domainRating: 16,
    viewsPerMonth: 8000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "SimilarSiteSearch",
    description: "Find similar websites and alternatives",
    url: "http://www.similarsitesearch.com/tips.html",
    bgColor: "#3b82f6",
    domainRating: 53,
    viewsPerMonth: 85000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Slant",
    description: "Community-driven product recommendations",
    url: "https://www.slant.co/",
    bgColor: "#2563eb",
    domainRating: 71,
    viewsPerMonth: 1200000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "SnapMunk",
    description: "Startup submission and discovery platform",
    url: "https://www.snapmunk.com/submit-your-startup/",
    bgColor: "#ef4444",
    domainRating: 60,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Software Advice",
    description: "Business software recommendations by Gartner",
    url: "https://softwareadvice-markets.questionpro.com/",
    bgColor: "#059669",
    domainRating: 84,
    submitDifficulty: SubmitDifficulty.Low,
    viewsPerMonth: 9500000,
    tags: [
      DirectoryTag.FreeLaunch,
      DirectoryTag.PaidFeatures,
      DirectoryTag.HighTraffic,
    ],
  },
  {
    name: "StackShare",
    description: "Developer tool discovery and tech stack sharing",
    url: "http://stackshare.io/",
    bgColor: "#0084ff",
    domainRating: 80,
    viewsPerMonth: 2800000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Startup 88",
    description: "Global startup directory and discovery platform",
    url: "https://startup88.com/",
    bgColor: "#f97316",
    domainRating: 26,
    viewsPerMonth: 38000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Base",
    description: "Submit and discover innovative startups",
    url: "https://startupbase.io/submit",
    bgColor: "#6366f1",
    domainRating: 52,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Beat",
    description: "Startup news and pitch submission platform",
    url: "http://startupbeat.com/startup-beat-featured-startup-pitch-guidelines/",
    bgColor: "#dc2626",
    domainRating: 55,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Benchmarks",
    description: "Startup metrics and benchmarking platform",
    url: "https://www.startupbenchmarks.com/",
    bgColor: "#0ea5e9",
    domainRating: 6,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Inspire",
    description: "Inspirational startup stories and submissions",
    url: "https://www.startupinspire.com/submit",
    bgColor: "#f59e0b",
    domainRating: 48,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Submit Co",
    description: "Inspirational startup stories and submissions",
    url: "https://submit.co/",
    bgColor: "#f53e0b",
    domainRating: 34,
    viewsPerMonth: 28000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Lift",
    description: "Startup discovery and launch platform",
    url: "http://www.startuplift.com/",
    bgColor: "#8b5cf6",
    domainRating: 38,
    viewsPerMonth: 55000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Ranking",
    description: "Global startup ranking and discovery platform",
    url: "http://www.startupranking.com/",
    bgColor: "#ef4444",
    domainRating: 68,
    viewsPerMonth: 125000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Register",
    description: "Register and discover new startups",
    url: "http://startupregister.net/register-your-startup/",
    bgColor: "#059669",
    domainRating: 3,
    viewsPerMonth: 15000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Stash",
    description: "Curated resources for entrepreneurs and startups",
    url: "http://startupstash.com/",
    bgColor: "#2563eb",
    domainRating: 68,
    viewsPerMonth: 285000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Tabs",
    description: "Browser homepage for startup discovery",
    url: "http://startuptabs.com/",
    bgColor: "#10b981",
    domainRating: 19,
    viewsPerMonth: 35000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startup Tracker",
    description: "Track and discover emerging startups",
    url: "https://startuptracker.io/",
    bgColor: "#0ea5e9",
    domainRating: 45,
    viewsPerMonth: 25000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "StartupBlink",
    description: "Global startup ecosystem map and rankings",
    url: "http://www.startupblink.com/",
    bgColor: "#f97316",
    domainRating: 70,
    viewsPerMonth: 420000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startups Gallery",
    description: "Visual gallery of innovative startups",
    url: "https://startups.gallery/",
    bgColor: "#7c3aed",
    domainRating: 16,
    viewsPerMonth: 18000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Startups List",
    description: "Comprehensive directory of startups worldwide",
    url: "https://www.startups-list.com/",
    bgColor: "#3b82f6",
    domainRating: 44,
    viewsPerMonth: 48000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "State of Tech",
    description: "Technology news and app review platform",
    url: "http://stateoftech.net/advertise?submit-an-app-for-review",
    bgColor: "#059669",
    domainRating: 42,
    viewsPerMonth: 85000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Tapscape",
    description: "Mobile app and tech product reviews",
    url: "https://www.tapscape.com/",
    bgColor: "#ef4444",
    domainRating: 55,
    viewsPerMonth: 320000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Tech Faster",
    description: "Technology news and startup submissions",
    url: "http://techfaster.com/submit-your-company/",
    bgColor: "#6366f1",
    domainRating: 42,
    viewsPerMonth: 65000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Tech Pluto",
    description: "Startup submission and tech news platform",
    url: "http://www.techpluto.com/submit-a-startup/",
    bgColor: "#8b5cf6",
    domainRating: 49,
    viewsPerMonth: 45000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "The iPhone Mom",
    description: "App reviews and family-focused technology",
    url: "https://www.theiphonemom.com/",
    bgColor: "#f59e0b",
    domainRating: 53,
    viewsPerMonth: 185000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Vator",
    description: "Startup news and entrepreneur network",
    url: "http://www.vator.tv/",
    bgColor: "#dc2626",
    domainRating: 74,
    viewsPerMonth: 280000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "VentureBeat",
    description: "Technology news and startup coverage",
    url: "http://venturebeat.com/news-tips/",
    bgColor: "#1e40af",
    domainRating: 91,
    viewsPerMonth: 8500000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "Web App Rater",
    description: "Web application review and rating service",
    url: "https://webapprater.com/submit-your-web-application-for-review-html",
    bgColor: "#10b981",
    domainRating: 37,
    viewsPerMonth: 22000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Website Hunt",
    description: "Discover and hunt for great websites",
    url: "https://www.websitehunt.co",
    bgColor: "#f97316",
    domainRating: 12,
    viewsPerMonth: 38000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
  {
    name: "Y Combinator",
    description: "The world's most powerful startup accelerator",
    url: "https://news.ycombinator.com/",
    bgColor: "#ff6600",
    domainRating: 90,
    submitDifficulty: SubmitDifficulty.Low,
    viewsPerMonth: 12500000,
    tags: [DirectoryTag.FreeLaunch, DirectoryTag.HighTraffic],
  },
  {
    name: "yesRamen",
    description: "Simple startup submission and discovery",
    url: "https://yesramen.com/",
    bgColor: "#ef4444",
    domainRating: 8,
    viewsPerMonth: 8000,
    submitDifficulty: SubmitDifficulty.Low,
    tags: [DirectoryTag.FreeLaunch],
  },
];

async function seedDirectories() {
  try {
    const mongoUri =
      "mongodb+srv://antonyefanov:9E9f3a4Antongogi@cluster0.xd3no.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";
    if (!mongoUri) {
      throw new Error("MONGODB_URI environment variable is not defined");
    }

    console.log("Connecting to MongoDB...");
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB successfully");

    // Clear existing directories (optional - remove if you want to keep existing data)
    console.log("Clearing existing directories...");
    await Directory.deleteMany({});
    console.log("Existing directories cleared");

    // Insert new directories
    console.log("Seeding directories...");
    const insertedDirectories = await Directory.insertMany(DIRECTORIES_V2);
    console.log(
      `Successfully seeded ${insertedDirectories.length} directories`,
    );

    // Log inserted directories for verification
    insertedDirectories.forEach((dir, index) => {
      console.log(`${index + 1}. ${dir.name} - ${dir.url}`);
    });

    console.log("Seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding directories:", error);
    process.exit(1);
  } finally {
    // Close MongoDB connection
    await mongoose.connection.close();
    console.log("MongoDB connection closed");
    process.exit(0);
  }
}

// Run the seed function
if (require.main === module) {
  seedDirectories();
}

export default seedDirectories;
